### ISSUE TITLE
[JENKINS-16073] Support for multiple Jira instances

### ISSUE THREAD

**Issue by rantoniuk** [rantoniuk/jira-plugin#148]
<p>I would like to be able to have the JIRA url, username and password configurable on a per-project basis. We have multiple projects and not all of them track in the same Jira.<br/>
Basically, all the info which is in the global config I'd like to be able to override in individual projects.</p>

---
<details><summary><i>Originally reported by <a title="scooper4711" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=scooper4711">scooper4711</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-16073" target="_blank">Support for multiple Jira instances</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2025-05-30
</ul></i>
</details>

**Comment by rantoniuk** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=michieldemey">michieldemey</a>:</i>
<p>This will currently throw a NullPointerException if multiple Jira sites are defined.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.NullPointerException
	at hudson.plugins.jira.pipeline.CommentStep$CommentStepExecution.run(CommentStep.java:86)
	at hudson.plugins.jira.pipeline.CommentStep$CommentStepExecution.run(CommentStep.java:68)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:52)
	at hudson.security.ACL.impersonate(ACL.java:221)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
</pre>
</div></div>

<p>Using the dsl in the Jenkinsfile</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">jiraComment(issueKey: <span class="code-quote">"KEY-01"</span>, body: <span class="code-quote">"My comment"</span>)
</pre>
</div></div>
